document.addEventListener('DOMContentLoaded', () => {
    const select = (selector) => document.querySelector(selector); const selectAll = (selector) => document.querySelectorAll(selector); const mobileMenuButton = select('.mobile-menu-button'); const mainNav = select('.main-nav'); const updateMenuState = (isOpen) => { if (!mobileMenuButton) return; mobileMenuButton.setAttribute('aria-expanded', isOpen ? 'true' : 'false'); mobileMenuButton.setAttribute('aria-label', isOpen ? 'Menüyü Kapat' : 'Menüyü Aç') }; if (mobileMenuButton && mainNav) { mobileMenuButton.addEventListener('click', () => { const willOpen = !mainNav.classList.contains('active'); mainNav.classList.toggle('active'); mobileMenuButton.classList.toggle('active'); document.body.classList.toggle('no-scroll', willOpen); updateMenuState(willOpen) }); mainNav.querySelectorAll('a').forEach(link => { link.addEventListener('click', () => { mainNav.classList.remove('active'); mobileMenuButton.classList.remove('active'); document.body.classList.remove('no-scroll'); updateMenuState(!1) }) }); document.addEventListener('keydown', (event) => { if (event.key === 'Escape' && mainNav.classList.contains('active')) { mainNav.classList.remove('active'); mobileMenuButton.classList.remove('active'); document.body.classList.remove('no-scroll'); updateMenuState(!1); mobileMenuButton.focus() } }) }
    const slides = selectAll('.slide'); if (slides.length > 0) {
        const sliderContainer = select('.slider-container'); const motionQuery = window.matchMedia ? window.matchMedia('(prefers-reduced-motion: reduce)') : null; let currentSlide = 0; let slideInterval; let sliderInitialized = !1; const showSlide = (n) => { slides.forEach((slide, index) => { slide.classList.toggle('active', index === n) }) }; const nextSlide = () => { currentSlide = (currentSlide + 1) % slides.length; showSlide(currentSlide) }; const stopSlider = () => { clearInterval(slideInterval); slideInterval = null }; const startSlider = () => {
            if (motionQuery?.matches) { stopSlider(); return }
            stopSlider(); slideInterval = setInterval(nextSlide, 5000)
        }; const initHeroSlider = () => {
            if (sliderInitialized) return; document.querySelectorAll('.slide img[data-src]').forEach(img => {
                if (img.dataset.srcset) { img.srcset = img.dataset.srcset; img.removeAttribute('data-srcset') }
                if (img.dataset.sizes) { img.sizes = img.dataset.sizes; img.removeAttribute('data-sizes') }
                img.src = img.dataset.src; img.removeAttribute('data-src'); img.loading = 'lazy'
            }); showSlide(0); if (!motionQuery?.matches) { startSlider() }
            sliderInitialized = !0
        }; motionQuery?.addEventListener('change', (event) => { if (!sliderInitialized) return; if (event.matches) { stopSlider() } else { startSlider() } }); const pauseInteractions = ['mouseenter', 'focusin', 'touchstart']; const resumeInteractions = ['mouseleave', 'focusout', 'touchend']; pauseInteractions.forEach(evt => sliderContainer?.addEventListener(evt, stopSlider)); resumeInteractions.forEach(evt => sliderContainer?.addEventListener(evt, () => {
            if (motionQuery?.matches) return; if (!sliderInitialized) { initHeroSlider(); return }
            startSlider()
        })); if ('IntersectionObserver' in window && sliderContainer) { const heroObserver = new IntersectionObserver((entries, observer) => { if (entries.some(entry => entry.isIntersecting)) { initHeroSlider(); observer.disconnect() } }, { threshold: 0.25 }); heroObserver.observe(sliderContainer) } else { initHeroSlider() }
    }
    const calculateBtn = select('#calculate-btn'); if (calculateBtn) { calculateBtn.addEventListener('click', () => { const area = parseFloat(select('#area').value); const servicePrice = parseFloat(select('#service-type').value); if (area > 0 && servicePrice > 0) { const cost = area * servicePrice; select('#estimated-cost').textContent = cost.toLocaleString('tr-TR', { minimumFractionDigits: 0, maximumFractionDigits: 0 }) + ' TL' } else { alert('Lütfen geçerli bir metrekare ve hizmet türü girin!') } }) }
    const quoteForm = select('#quote-form'); if (quoteForm) {
        quoteForm.addEventListener('submit', (e) => {
            e.preventDefault(); const name = select('#name').value.trim(); const phone = select('#phone').value.trim(); const district = select('#district') ? select('#district').value.trim() : ''; const service = select('#service') ? select('#service').value.trim() : ''; const email = select('#email') ? select('#email').value.trim() : ''; const message = select('#message') ? select('#message').value.trim() : ''; if (typeof grecaptcha !== "undefined") { let recaptchaResponse = grecaptcha.getResponse(); if (!recaptchaResponse) { alert('Lütfen doğrulama testi (reCAPTCHA) çözün.'); return } }
            if (!name || !phone || !district || !service) { alert('Lütfen zorunlu alanları doldurun (Adınız Soyadınız, Telefon, İlçe/Semt ve Hizmet Türü)'); return }
            let waMessage = `Yeni Teklif Talebi:%0A` + `Ad Soyad: ${name}%0A` + `Telefon: ${phone}%0A` + (email ? `E-posta: ${email}%0A` : "") + `İlçe/Semt: ${district}%0A` + `Hizmet Türü: ${service}%0A` + (message ? `Mesaj: ${message}%0A` : ""); let whatsappNo = '905078322912'; let waURL = `https://wa.me/${whatsappNo}?text=${waMessage}`; window.open(waURL, '_blank'); quoteForm.reset()
        })
    }
    document.body.addEventListener('click', (e) => { const anchor = e.target.closest('a[href^="#"]'); if (!anchor || anchor.getAttribute('href') === '#') return; e.preventDefault(); const targetElement = select(anchor.getAttribute('href')); if (targetElement) { const headerOffset = 70; const targetTop = window.scrollY + targetElement.getBoundingClientRect().top - headerOffset; window.scrollTo({ top: targetTop, behavior: 'smooth' }); if (mainNav && mainNav.classList.contains('active')) { mainNav.classList.remove('active'); mobileMenuButton.classList.remove('active'); document.body.classList.remove('no-scroll'); updateMenuState(!1) } } }); const testimonialSlider = select('.testimonial-slider'); if (testimonialSlider) {
        const testimonials = selectAll('.testimonial'); const prevBtn = select('#prev-testimonial'); const nextBtn = select('#next-testimonial'); const indicatorsContainer = select('#slider-indicators'); let currentTestimonial = 0; let testimonialInterval; const overflowCache = new WeakMap(); const recalculateOverflow = () => { testimonials.forEach(testimonial => { const p = testimonial.querySelector('p'); if (!p) return; overflowCache.set(testimonial, p.scrollHeight > p.clientHeight + 5) }) }; if (indicatorsContainer && testimonials.length > 0) { indicatorsContainer.innerHTML = ''; const fragment = document.createDocumentFragment(); testimonials.forEach((testimonial, index) => { const dot = document.createElement('div'); dot.classList.add('dot'); dot.setAttribute('role', 'button'); dot.setAttribute('aria-label', `${index + 1}. yoruma git`); dot.setAttribute('tabindex', '0'); if (index === 0) dot.classList.add('active'); const goToSlide = () => { showTestimonial(index); resetAutoSlide() }; dot.addEventListener('click', (e) => { e.stopPropagation(); goToSlide() }); dot.addEventListener('keydown', (e) => { if (e.key === 'Enter' || e.key === ' ') { e.preventDefault(); goToSlide() } }); fragment.appendChild(dot); const p = testimonial.querySelector('p'); if (p) { if (!testimonial.querySelector('.read-more-btn')) { const btn = document.createElement('button'); btn.className = 'read-more-btn'; btn.textContent = 'Daha Fazla Göster'; btn.setAttribute('aria-expanded', 'false'); btn.type = 'button'; btn.addEventListener('click', (e) => { e.stopPropagation(); const isExpanded = testimonial.classList.toggle('expanded'); btn.textContent = isExpanded ? 'Daha Az Göster' : 'Daha Fazla Göster'; btn.setAttribute('aria-expanded', isExpanded); if (isExpanded) { stopAutoSlide() } else { startAutoSlide() } }); p.insertAdjacentElement('afterend', btn) } } }); indicatorsContainer.appendChild(fragment); requestAnimationFrame(recalculateOverflow); window.addEventListener('resize', recalculateOverflow, { passive: !0 }) }
        const dots = selectAll('.slider-indicators .dot'); const showTestimonial = (n) => {
            testimonials.forEach(t => { t.classList.remove('active'); t.classList.remove('expanded'); const btn = t.querySelector('.read-more-btn'); if (btn) { btn.textContent = 'Daha Fazla Göster'; btn.style.display = 'none' } }); dots.forEach(d => d.classList.remove('active')); if (testimonials[n]) { const t = testimonials[n]; t.classList.add('active'); const btn = t.querySelector('.read-more-btn'); if (btn) { btn.style.display = overflowCache.get(t) ? 'block' : 'none' } }
            if (dots[n]) dots.forEach(d => d.classList.remove('active')); if (dots[n]) dots[n].classList.add('active'); currentTestimonial = n
        }; const nextTestimonial = () => { let next = (currentTestimonial + 1) % testimonials.length; showTestimonial(next) }; const prevTestimonial = () => { let prev = (currentTestimonial - 1 + testimonials.length) % testimonials.length; showTestimonial(prev) }; const startAutoSlide = () => { stopAutoSlide(); testimonialInterval = setInterval(nextTestimonial, 7000) }; const stopAutoSlide = () => { if (testimonialInterval) { clearInterval(testimonialInterval); testimonialInterval = null } }; const resetAutoSlide = () => { stopAutoSlide(); startAutoSlide() }; if (prevBtn) prevBtn.addEventListener('click', () => { prevTestimonial(); resetAutoSlide() }); if (nextBtn) nextBtn.addEventListener('click', () => { nextTestimonial(); resetAutoSlide() }); const testimonialContainer = select('.testimonial-container'); if (testimonialContainer) { testimonialContainer.addEventListener('click', () => { nextTestimonial(); resetAutoSlide() }); testimonialContainer.style.cursor = 'pointer' }
        testimonialSlider.addEventListener('mouseenter', stopAutoSlide); testimonialSlider.addEventListener('mouseleave', startAutoSlide); testimonialSlider.addEventListener('touchstart', stopAutoSlide, { passive: !0 }); testimonialSlider.addEventListener('touchend', startAutoSlide, { passive: !0 }); if (testimonials.length > 0) { showTestimonial(0); startAutoSlide() }
    }
    const faqItems = document.querySelectorAll('.faq-item'); const searchInput = document.getElementById('faq-search'); const faqIndex = Array.from(faqItems).map(item => { const questionEl = item.querySelector('.faq-question'); const answerEl = item.querySelector('.faq-answer'); return { item, questionEl, questionText: questionEl?.textContent.toLowerCase() || '', answerText: answerEl?.textContent.toLowerCase() || '' } }); faqItems.forEach(item => { const question = item.querySelector('.faq-question'); question.addEventListener('click', () => { faqItems.forEach(otherItem => { if (otherItem !== item) otherItem.classList.remove('active'); }); item.classList.toggle('active') }) }); if (searchInput) { let searchDebounce; searchInput.addEventListener('input', function () { clearTimeout(searchDebounce); const term = this.value.toLowerCase().trim(); searchDebounce = setTimeout(() => { faqIndex.forEach(({ item, questionText, answerText }) => { const matches = !term || questionText.includes(term) || answerText.includes(term); item.style.display = matches ? 'block' : 'none'; if (matches && term && answerText.includes(term) && !item.classList.contains('active')) { item.classList.add('active') } if (!term) { item.classList.remove('active') } }) }, 120) }) }
    const readMoreBtn = select('#read-more-btn'); const moreContent = select('#more-content'); if (readMoreBtn && moreContent) { readMoreBtn.addEventListener('click', function () { const isVisible = moreContent.style.display === 'block'; moreContent.style.display = isVisible ? 'none' : 'block'; this.innerHTML = isVisible ? 'Daha Fazla Bilgi <i class="fas fa-chevron-down"></i>' : 'Daha Az Göster <i class="fas fa-chevron-up"></i>' }) }
})